"""change reservation status again

Revision ID: 23d10a9ffd11
Revises: af4fc8f80c79
Create Date: 2023-11-10 20:29:31.615844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23d10a9ffd11'
down_revision = 'af4fc8f80c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('reservation_status',
               existing_type=mysql.ENUM('reserved', 'unreserved'),
               type_=sa.Boolean(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('reservation_status',
               existing_type=sa.Boolean(),
               type_=mysql.ENUM('reserved', 'unreserved'),
               existing_nullable=False)

    # ### end Alembic commands ###
