"""change reservation status

Revision ID: af4fc8f80c79
Revises: 4fbe00d89688
Create Date: 2023-11-10 20:03:03.660097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af4fc8f80c79'
down_revision = '4fbe00d89688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('reservation_status',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Enum('reserved', 'unreserved', name='reservationstatus'),
               existing_nullable=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('ix_roles_is_admin')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.create_index('ix_roles_is_admin', ['is_admin'], unique=False)

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('reservation_status',
               existing_type=sa.Enum('reserved', 'unreserved', name='reservationstatus'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)

    # ### end Alembic commands ###
